/**
 * AUTO-GENERATED by scripts/build-tokens.ts — DO NOT EDIT
 * Source: design/tokens/*.json
 * Checksum: 0257b08a37cfe65ee74e0c41fd2ba25ed3e10177758b8c7b5d5623e9cc74c5bc
 */
export const cssVars = {
  "--color-fg-default": "222 47% 11%",
  "--color-fg-secondary": "215 19% 35%",
  "--color-fg-muted": "215 16% 47%",
  "--color-fg-disabled": "215 20% 65%",
  "--color-fg-onbrand": "0 0% 100%",
  "--color-fg-reversed": "0 0% 100%",
  "--color-fg-brand": "221 83% 53%",
  "--color-fg-brand-hover": "224 76% 48%",
  "--color-fg-success": "142 76% 36%",
  "--color-fg-error": "0 72% 51%",
  "--color-fg-warning": "32 95% 44%",
  "--color-bg-canvas": "0 0% 100%",
  "--color-bg-surface": "210 40% 98%",
  "--color-bg-secondary": "210 40% 96%",
  "--color-bg-tertiary": "214 32% 91%",
  "--color-bg-brand": "221 83% 53%",
  "--color-bg-brand-hover": "224 76% 48%",
  "--color-bg-success": "138 76% 97%",
  "--color-bg-error": "0 86% 97%",
  "--color-bg-warning": "48 100% 96%",
  "--color-bg-reversed": "222 47% 11%",
  "--color-bg-scrim-light": "rgba(15, 23, 42, 0.25)",
  "--color-bg-scrim-medium": "rgba(15, 23, 42, 0.50)",
  "--color-bg-scrim-dark": "rgba(15, 23, 42, 0.75)",
  "--color-border-default": "213 27% 84%",
  "--color-border-hover": "215 20% 65%",
  "--color-border-focus": "221 83% 53%",
  "--color-border-error": "0 72% 51%",
  "--color-border-success": "142 76% 36%",
  "--color-state-success": "142 76% 36%",
  "--color-state-warn": "32 95% 44%",
  "--color-state-danger": "0 72% 51%",
  "--color-state-info": "221 83% 53%",
  "--color-state-selected": "214 100% 97%"
} as const;
