/**
 * AUTO-GENERATED by scripts/build-tokens.ts — DO NOT EDIT
 * Source: design/tokens/*.json
 * Checksum: 0257b08a37cfe65ee74e0c41fd2ba25ed3e10177758b8c7b5d5623e9cc74c5bc
 */
export const themeExtensions = {
  colors: {
  "fg": {
    "default": "hsl(var(--color-fg-default) / <alpha-value>)",
    "secondary": "hsl(var(--color-fg-secondary) / <alpha-value>)",
    "muted": "hsl(var(--color-fg-muted) / <alpha-value>)",
    "disabled": "hsl(var(--color-fg-disabled) / <alpha-value>)",
    "onbrand": "hsl(var(--color-fg-onbrand) / <alpha-value>)",
    "reversed": "hsl(var(--color-fg-reversed) / <alpha-value>)",
    "brand": "hsl(var(--color-fg-brand) / <alpha-value>)",
    "brand-hover": "hsl(var(--color-fg-brand-hover) / <alpha-value>)",
    "success": "hsl(var(--color-fg-success) / <alpha-value>)",
    "error": "hsl(var(--color-fg-error) / <alpha-value>)",
    "warning": "hsl(var(--color-fg-warning) / <alpha-value>)"
  },
  "bg": {
    "canvas": "hsl(var(--color-bg-canvas) / <alpha-value>)",
    "surface": "hsl(var(--color-bg-surface) / <alpha-value>)",
    "secondary": "hsl(var(--color-bg-secondary) / <alpha-value>)",
    "tertiary": "hsl(var(--color-bg-tertiary) / <alpha-value>)",
    "brand": "hsl(var(--color-bg-brand) / <alpha-value>)",
    "brand-hover": "hsl(var(--color-bg-brand-hover) / <alpha-value>)",
    "success": "hsl(var(--color-bg-success) / <alpha-value>)",
    "error": "hsl(var(--color-bg-error) / <alpha-value>)",
    "warning": "hsl(var(--color-bg-warning) / <alpha-value>)",
    "reversed": "hsl(var(--color-bg-reversed) / <alpha-value>)",
    "scrim-light": "hsl(var(--color-bg-scrim-light) / <alpha-value>)",
    "scrim-medium": "hsl(var(--color-bg-scrim-medium) / <alpha-value>)",
    "scrim-dark": "hsl(var(--color-bg-scrim-dark) / <alpha-value>)"
  },
  "border": {
    "default": "hsl(var(--color-border-default) / <alpha-value>)",
    "hover": "hsl(var(--color-border-hover) / <alpha-value>)",
    "focus": "hsl(var(--color-border-focus) / <alpha-value>)",
    "error": "hsl(var(--color-border-error) / <alpha-value>)",
    "success": "hsl(var(--color-border-success) / <alpha-value>)"
  },
  "state": {
    "success": "hsl(var(--color-state-success) / <alpha-value>)",
    "warn": "hsl(var(--color-state-warn) / <alpha-value>)",
    "danger": "hsl(var(--color-state-danger) / <alpha-value>)",
    "info": "hsl(var(--color-state-info) / <alpha-value>)",
    "selected": "hsl(var(--color-state-selected) / <alpha-value>)"
  }
},
  spacing: {
  "0": "0px",
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "20px",
  "6": "24px",
  "8": "32px",
  "10": "40px",
  "12": "48px",
  "0.5": "2px",
  "1.5": "6px",
  "2.5": "10px"
},
  borderRadius: {
  "none": "0px",
  "sm": "4px",
  "md": "8px",
  "lg": "12px",
  "xl": "16px",
  "full": "9999px"
},
  boxShadow: {
  "sm": "0 1px 2px 0 rgba(0,0,0,0.05)",
  "md": "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
  "lg": "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)"
},
  fontSize: {
  "xs": [
    "0.75rem",
    {
      "lineHeight": "1rem"
    }
  ],
  "sm": [
    "0.875rem",
    {
      "lineHeight": "1.25rem"
    }
  ],
  "md": [
    "1rem",
    {
      "lineHeight": "1.5rem"
    }
  ],
  "lg": [
    "1.125rem",
    {
      "lineHeight": "1.75rem"
    }
  ],
  "xl": [
    "1.25rem",
    {
      "lineHeight": "1.75rem"
    }
  ],
  "2xl": [
    "1.5rem",
    {
      "lineHeight": "2rem"
    }
  ]
}
} as const;
